# Generated by Django 4.2.6 on 2023-10-13 20:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePredictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgae', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
            ],
        ),
    ]
