# Generated by Django 4.2.6 on 2023-10-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepredictmodel',
            old_name='imgae',
            new_name='image',
        ),
    ]
